//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.DataAccess.EF.ModelFirstMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdditionalInformation
    {
        public long Id { get; set; }
        public string FacebookAccount { get; set; }
        public string GoogleAccount { get; set; }
        public string TwitterAccount { get; set; }
        public string GoldenLineAccount { get; set; }
        public string LinkInAccount { get; set; }
        public byte DataState { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
