//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.DataAccess.EF.ModelFirstMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class BenefitsProfit
    {
        public long Id { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public double BenefitBrutto { get; set; }
        public double BenefitNetto { get; set; }
        public int BenefitType { get; set; }
        public double Retirement { get; set; }
        public double Disability { get; set; }
        public double Sikness { get; set; }
        public double Health { get; set; }
        public double Taxable { get; set; }
        public double AdvanceAt_PIT { get; set; }
        public long PersonId { get; set; }
        public byte DataState { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
