//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.DataAccess.EF.ModelFirstMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson
    {
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Street { get; set; }
        public int BuildingNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public byte DataState { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
        public long PersonId { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
