//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.DataAccess.EF.ModelFirstMapping
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AdditionalInformation> AdditionalInformations { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<BenefitsProfit> BenefitsProfits { get; set; }
        public virtual DbSet<Collage> Collages { get; set; }
        public virtual DbSet<CompaniesDictionary> CompaniesDictionaries { get; set; }
        public virtual DbSet<ContactPerson> ContactPersons { get; set; }
        public virtual DbSet<Contract> Contracts { get; set; }
        public virtual DbSet<Delegation> Delegations { get; set; }
        public virtual DbSet<Employment> Employments { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<OrganiziationalUnit> OrganiziationalUnits { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Traning> Tranings { get; set; }
        public virtual DbSet<Vacation> Vacations { get; set; }
        public virtual DbSet<WorkRegistry> WorkRegistrys { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<College> Colleges { get; set; }
        public virtual DbSet<Position> Positions { get; set; }
        public virtual DbSet<AccountLog> AccountLogs { get; set; }
        public virtual DbSet<CourseMaterial> CourseMaterials { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<PromotialMaterial> PromotialMaterials { get; set; }
        public virtual DbSet<VacationDocument> VacationDocuments { get; set; }
    }
}
