//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HR.DataAccess.EF.ModelFirstMapping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Accounts = new HashSet<Account>();
            this.AdditionalInformations = new HashSet<AdditionalInformation>();
            this.BenefitsProfits = new HashSet<BenefitsProfit>();
            this.Collages = new HashSet<Collage>();
            this.ContactPersons = new HashSet<ContactPerson>();
            this.Delegations = new HashSet<Delegation>();
            this.Employments = new HashSet<Employment>();
            this.Jobs = new HashSet<Job>();
            this.OrganiziationalUnits = new HashSet<OrganiziationalUnit>();
            this.Persons1 = new HashSet<Person>();
            this.Tranings = new HashSet<Traning>();
            this.Vacations = new HashSet<Vacation>();
            this.WorkRegistrys = new HashSet<WorkRegistry>();
            this.CourseMaterials = new HashSet<CourseMaterial>();
            this.Documents = new HashSet<Document>();
            this.PromotialMaterials = new HashSet<PromotialMaterial>();
        }
    
        public long Id { get; set; }
        public string FirstName { get; set; }
        public string Surname { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string Street { get; set; }
        public int BuildingNumber { get; set; }
        public Nullable<int> ApartmentNumber { get; set; }
        public decimal Phone { get; set; }
        public string Email { get; set; }
        public decimal NIP { get; set; }
        public string IDCard { get; set; }
        public string PESEL { get; set; }
        public Nullable<long> ManagerId { get; set; }
        public byte DataState { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> EditDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<AdditionalInformation> AdditionalInformations { get; set; }
        public virtual ICollection<BenefitsProfit> BenefitsProfits { get; set; }
        public virtual ICollection<Collage> Collages { get; set; }
        public virtual ICollection<ContactPerson> ContactPersons { get; set; }
        public virtual ICollection<Delegation> Delegations { get; set; }
        public virtual ICollection<Employment> Employments { get; set; }
        public virtual ICollection<Job> Jobs { get; set; }
        public virtual ICollection<OrganiziationalUnit> OrganiziationalUnits { get; set; }
        public virtual ICollection<Person> Persons1 { get; set; }
        public virtual Person Person1 { get; set; }
        public virtual ICollection<Traning> Tranings { get; set; }
        public virtual ICollection<Vacation> Vacations { get; set; }
        public virtual ICollection<WorkRegistry> WorkRegistrys { get; set; }
        public virtual ICollection<CourseMaterial> CourseMaterials { get; set; }
        public virtual ICollection<Document> Documents { get; set; }
        public virtual ICollection<PromotialMaterial> PromotialMaterials { get; set; }
    }
}
